name: build-page
run-name: ${{ github.actor }} is building the static page from the code and posts

on: [push, workflow_dispatch]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4

      - name: Install node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # `elm-pages build` will fail if lamdera is not installed. 
      # It is made its own step because it has several steps.
      - name: Install lamdera
        run: |
          curl https://static.lamdera.com/bin/lamdera-1.2.0-linux-x86_64 -o /usr/local/bin/lamdera
          chmod a+x /usr/local/bin/lamdera

      # `elm-pages build` will fail if these tools are not installed.
      - name: Install tools that are needed by elm-pages
        run: | 
          npm install -g elm-optimize-level-2@0.3.5
          npm install -g elm-review@2.11.2
          npm install -g elm-format@0.8.7

      - name: Build page
        run: npx elm-pages@3.0.15 build

      # Zip the files generated by `elm-pages build` into a .tar.gz so that they can be uploaded to GitHub Pages.
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/

  deploy:
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
